// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyMgt.Data;

#nullable disable

namespace StudyMgt.Migrations
{
    [DbContext(typeof(StudyMgtDbContext))]
    [Migration("20260514124708_AddCentreAdminPasswordReset")]
    partial class AddCentreAdminPasswordReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyMgt.Data.Entities.ApplicationAuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ActorUsername")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PagePath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("PagePath");

                    b.ToTable("ApplicationAuditLogs");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CarerConsentAuditEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarerOnboardingId")
                        .HasColumnType("integer");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("CarerOnboardingId");

                    b.HasIndex("Timestamp");

                    b.ToTable("CarerConsentAuditEntries");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CarerOnboardingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CarerId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("ConfirmAccuracyAndTruth")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("DailyUpdatesConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DailyUpdatesConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("DailyUpdatesWithdrawn")
                        .HasColumnType("boolean");

                    b.Property<bool>("DataRetentionCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataRetentionExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EHCPStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasParentalResponsibility")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LegitimateInterestConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LegitimateInterestConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicalAndAccessibilityInfo")
                        .HasColumnType("text");

                    b.Property<string>("MedicalAndAccessibilityInfo2")
                        .HasColumnType("text");

                    b.Property<bool>("NoRestrictiveOrders")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PhotosVideosConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PhotosVideosConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("PhotosVideosWithdrawn")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredContactMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PrivacyNoticeAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PrivacyNoticeAcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Relationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StudentDateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StudentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ThirdPartySharingConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ThirdPartySharingConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("ThirdPartySharingWithdrawn")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CarerId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("CarerOnboardings");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CarerPortalAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarerOnboardingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CarerOnboardingId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("CarerPortalAccounts");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CentreAdminPasswordResetTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentreAdminAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("CentreAdminPortalAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("ResetToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CentreAdminAccountId");

                    b.ToTable("CentreAdminPasswordResetTokens");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CentreAdminPortalAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPasswordChangedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CentreAdminPortalAccounts");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.DbRoundTripLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DbRoundTripLogs");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.StudentConsentRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsConsented")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentOnboardingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecordedDate");

                    b.HasIndex("StudentOnboardingId");

                    b.ToTable("StudentConsentRecords");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.StudentOnboardingAuditEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldChanged")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("StudentOnboardingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedDate");

                    b.HasIndex("StudentOnboardingId");

                    b.ToTable("StudentOnboardingAudits");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.StudentOnboardingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssignedTutorId")
                        .HasColumnType("integer");

                    b.Property<string>("AssignedTutorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ConsentDataSharing")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentEmailCommunication")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentPhotos")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentSMSCommunication")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeclarationConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EHCPDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("EHCPStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ILPSummary")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MedicalInformation")
                        .HasColumnType("text");

                    b.Property<string>("PreferredContactMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PrivacyNoticeAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("RelationshipToStudent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresBehaviorSupport")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresCommunicationSupport")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresHearingSupport")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresPhysicalAccommodation")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresVisualSupport")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskAssessmentNotes")
                        .HasColumnType("text");

                    b.Property<string>("SENIndicators")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SafeguardingNotes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StudentIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedDate");

                    b.ToTable("StudentOnboardings");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.TutorOnboardingAuditEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldChanged")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("TutorOnboardingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedDate");

                    b.HasIndex("TutorOnboardingId");

                    b.ToTable("TutorOnboardingAudits");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.TutorOnboardingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsentDBSCheck")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentDataProcessing")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentMarketing")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConsentReferences")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractTerms")
                        .HasColumnType("text");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DBSCertificateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DBSCheckType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DBSExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DBSIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DBSStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeclarationConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HighestQualification")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OtherQualifications")
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PrivacyNoticeAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("Reference1Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reference1Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference2Contact")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reference2Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RightToWorkStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SafeguardingTrainingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SafeguardingTrainingExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SafeguardingTrainingStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeachingExperience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainingProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("VisaExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisaType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedDate");

                    b.ToTable("TutorOnboardings");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.TutorPortalAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TutorOnboardingId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TutorOnboardingId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TutorPortalAccounts");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CarerConsentAuditEntryEntity", b =>
                {
                    b.HasOne("StudyMgt.Data.Entities.CarerOnboardingEntity", "CarerOnboarding")
                        .WithMany("ConsentAuditEntries")
                        .HasForeignKey("CarerOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarerOnboarding");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CarerPortalAccountEntity", b =>
                {
                    b.HasOne("StudyMgt.Data.Entities.CarerOnboardingEntity", "CarerOnboarding")
                        .WithOne()
                        .HasForeignKey("StudyMgt.Data.Entities.CarerPortalAccountEntity", "CarerOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarerOnboarding");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CentreAdminPasswordResetTokenEntity", b =>
                {
                    b.HasOne("StudyMgt.Data.Entities.CentreAdminPortalAccountEntity", "CentreAdminAccount")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("CentreAdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentreAdminAccount");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.StudentConsentRecordEntity", b =>
                {
                    b.HasOne("StudyMgt.Data.Entities.StudentOnboardingEntity", "StudentOnboarding")
                        .WithMany("ConsentRecords")
                        .HasForeignKey("StudentOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentOnboarding");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.StudentOnboardingAuditEntity", b =>
                {
                    b.HasOne("StudyMgt.Data.Entities.StudentOnboardingEntity", "StudentOnboarding")
                        .WithMany("Audits")
                        .HasForeignKey("StudentOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentOnboarding");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.TutorOnboardingAuditEntity", b =>
                {
                    b.HasOne("StudyMgt.Data.Entities.TutorOnboardingEntity", "TutorOnboarding")
                        .WithMany("Audits")
                        .HasForeignKey("TutorOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TutorOnboarding");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.TutorPortalAccountEntity", b =>
                {
                    b.HasOne("StudyMgt.Data.Entities.TutorOnboardingEntity", "TutorOnboarding")
                        .WithOne()
                        .HasForeignKey("StudyMgt.Data.Entities.TutorPortalAccountEntity", "TutorOnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TutorOnboarding");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CarerOnboardingEntity", b =>
                {
                    b.Navigation("ConsentAuditEntries");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.CentreAdminPortalAccountEntity", b =>
                {
                    b.Navigation("PasswordResetTokens");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.StudentOnboardingEntity", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("ConsentRecords");
                });

            modelBuilder.Entity("StudyMgt.Data.Entities.TutorOnboardingEntity", b =>
                {
                    b.Navigation("Audits");
                });
#pragma warning restore 612, 618
        }
    }
}
